version: '3.8'
services:
  bitcoin_mining_simulation:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8521:8521"
    volumes:
      - ./:/app
    environment:
      - PYTHONUNBUFFERED=1
    command: ["python", "bitcoin_mining_simulation.py"]
